[package]
name = "iced_aw"
version = "0.7.0"
authors = [
    "Kaiden42 <gitlab@tinysn.com>",
    "Andrew Wheeler <genusistimelord@gmail.com>",
]
edition = "2021"
description = "Additional widgets for the Iced GUI library"
license = "MIT"
repository = "https://github.com/iced-rs/iced_aw"
# TODO documentation
readme = "README.md"
keywords = ["gui", "graphics", "interface", "widgets", "iced"]
categories = ["gui"]

[features]
badge = []
card = []
date_picker = ["chrono", "once_cell", "icons"]
color_picker = ["icons", "iced_widget/canvas"]
cupertino = ["iced_widget/canvas", "time"]
floating_element = []
grid = ["itertools"]
glow = []                                                   # TODO
icons = []
modal = []
tab_bar = []
tabs = ["tab_bar"]
time_picker = ["chrono", "icons", "iced_widget/canvas"]
wrap = []
number_input = ["num-traits"]
selection_list = []
split = []
menu = []
quad = []
spinner = []
context_menu = []
segmented_button = []
slide_bar = []
old_grid = []

default = [
    "badge",
    "card",
    "number_input",
    "date_picker",
    "color_picker",
    "floating_element",
    "grid",
    "modal",
    "tab_bar",
    "tabs",
    "time_picker",
    "slide_bar",
    "wrap",
    "selection_list",
    "split",
    #"menu",
    "quad",
    "context_menu",
    "spinner",
    "cupertino",
    "segmented_button",
    "num-traits",
    "old_grid"
]

[dependencies]
cfg-if = "1.0"
num-traits = { version = "0.2.16", optional = true }
time = { version = "0.3.23", features = ["local-offset"], optional = true }
chrono = { version = "0.4.26", optional = true }
once_cell = { version = "1.18.0", optional = true }
itertools = { version = "0.11.0", optional = true }
serde = "1.0"


[dependencies.iced_widget]
path = "../iced/widget"
# git = "https://github.com/iced-rs/iced.git"
#rev = "b474a2b7a763dcde6a377cb409001a7b5285ee8d"
#version = "0.1.1"

#[dependencies.iced_renderer]
#git = "https://github.com/iced-rs/iced.git"
#rev = "751ea77c29f6eb3d00f45f0a04c833a1d03a425c"
#features = ["wgpu"]
#version = "0.1.1"

[profile.dev.package."*"]
opt-level = 2

[workspace]
members = [
    "examples/badge",
    "examples/card",
    "examples/color_picker",
    "examples/cupertino/cupertino_button",
    "examples/cupertino/cupertino_spinner",
    "examples/cupertino/cupertino_switch",
    "examples/date_picker",
    "examples/floating_element",
    "examples/floating_element_anchors",
    "examples/grid",
    "examples/modal",
    "examples/modal_component",
    "examples/multiple_modals",
    "examples/tab_bar",
    "examples/tabs",
    "examples/time_picker",
    "examples/wrap",
    "examples/number_input",
    "examples/selection_list",
    "examples/split",
    "examples/split_scroller",
    #"examples/menu",
    "examples/spinner",
    "examples/context_menu",
    "examples/WidgetIDReturn",
    "examples/segmented_button",
    "examples/sliderbar",
]

[workspace.dependencies.iced]
path = "../iced"
# git = "https://github.com/iced-rs/iced.git"
#rev = "b474a2b7a763dcde6a377cb409001a7b5285ee8d"
#version = "0.10.0"
features = ["advanced", "lazy", "tokio"]

[workspace.dependencies.iced_aw]
path = "./"
default-features = false
features = ["num-traits"]
